app/analytics/query.test.ts, app/analytics/query.ts, app/components/TimeSeriesChart.tsx, app/routes/dashboard.tsx, package.json, server.ts
Fixes #6
- Local timezone is extracted from `cf` property and passed as context to loader
- Results by day now use local timezone to determine start of day
- Internally, dates are now consistently represented in UTC, but on display converted to local time (i.e. in chart)
- Tests now set timezone (via env variables) and incorporate timezone in results
=> Properly reflect results in local timezone

app/routes/dashboard.test.tsx
The exception was caused because if you do not send a valid country code, the country name formatter will explode. The mock test data was sending "Canada", "United States", etc. when it should have been sending "CA", "US', etc.
This patch just addresses the input data so that the tests run (and adds some assertions, which should have been there from the beginning). The fundamental problem is still there: the Dashboard will choke if it's fed non-country code values, and since there's no input validation on event ingestion, anyone could inject such values via `/collect` and cause a user's tracker to crash. Needs a follow-up.
Fixes #21
=> Fix exception thrown in dashboard route test

app/analytics/query.ts, app/routes/dashboard.test.tsx
Trying to improve test coverage. Needs to cover more failure cases.
=> Add test for dashboard loader

app/analytics/query.test.ts, app/routes/dashboard.test.tsx, app/routes/dashboard.tsx
This has a couple of benefits:
* After redirect, doesn't wait for `getSitesOrderedByHits` to finish before querying data (no blocking before fetching data; faster)
* Avoids situations where different URLs could generate the same document (better consistency IMO), i.e. we were loading a default site at `/dashboard` and this would generate the same document as `/dashboard?site=default`
* No longer throws when there is no data in the AE dataset (fixes #24)
* Removes unnecessary Promise layer in test code (when mocking responses via `fetch.mockResolvedValue)`
=> When no site provided on query string, redirect w/ with valid site specified

app/analytics/query.ts, app/analytics/schema.ts, app/routes/dashboard.tsx
Reimplements the types from https://github.com/benvinegar/counterscale/pull/26 with some small improvements, and the runtime checks removed.
=> Improve types for query

.husky/pre-commit, app/analytics/collect.test.ts, app/analytics/query.ts, app/entry.server.tsx, tsconfig.json
Setting `skipLibCheck` prevents typescript from checking your node_modules for errors. With this setting on, there were only a couple of small things to clean up, which means you can enforce type correctness.
This is probably better as a ci check rather than precommit hook, let me know if you agree and I can change it.
=> Configure ts so it doesnt error on lib types, allowing it to be enabled precommit (or in ci)

.eslintrc.cjs, app/analytics/collect.test.ts, app/analytics/query.test.ts, app/analytics/query.ts, app/components/TableCard.tsx, app/components/TimeSeriesChart.tsx, app/routes/dashboard.test.tsx, app/routes/dashboard.tsx
Removed last remaining explicit `any`. 
I would recommend dropping `prop-types` as a dependency and using typescript for the components as well, as the api is pretty verbose and not as expressive. On top of that, PropTypes perform a runtime typecheck, but ideally runtime type checking should be happening at the API boundaries, allowing us to trust typescript throughout the rest of the application. 
Because PropTypes performs runtime type checking, this PR should not be treated as type level only changes. 
Closes #13
=> Enable no explicit any

.github/workflows/ci.yaml
Now that types are in place, it would be a good idea to enforce proper types on PRs before merging.
=> Adds typechecking to the ci checks

app/components/TableCard.tsx
Fix #42 
Removed the extra `relative` classes, which were causing the issue on FireFox.
=> Fix table rows on Firefox

app/analytics/query.ts, app/components/TableCard.tsx, app/routes/dashboard.test.tsx, app/routes/dashboard.tsx
Introduces a new method, `getAllCountsByColumn`, which returns `visits`, `views`, and `visitors` for a given column (e.g. path, referrer, etc). Then modifies the "Counts by Path" table card to fetch that data and render multiple columns.
I decided to sort by visitors, because that's usually what I care about, but it could be views instead.
Fixes #12
=> Render views + visitors in table card by path

app/analytics/query.ts, app/routes/dashboard.tsx
Fix #61 (and might also ref #60)
This uses `dayjs` to increment hours and days when generating buckets in JS (to account for a lack of `COALESCE` SQL function in CF AE, see comment below), vs using fixed intervals which didn't account for DST boundaries and introduced other issues (naive mistake, oops).
This deserves to have tests. I tried doing an initial test for the DST boundaries but couldn't replicate the behavior I was experiencing when running the dev server (possibly because the Date object is mocked in `vitest` – not sure, haven't spent much time looking into this).
=> Fix bad date calculations along DST boundaries

app/analytics/query.ts
Fixes #60 
Originally this tried to do some clever tz math inside Analytics Engine, but it doesn't work. Instead just explicitly calculate the utc start time, treat everything as utc, then convert back to local during UI rendering.
Also removes `formatDateString` because I think it was also doing some implicit timezone conversion in there somewhere. I found `dayjs` to be more predictable.
=> Fix bad hourly start timestamp on chart data

app/components/TableCard.tsx, app/components/ui/table.tsx
This fixes the background color on table rows not going all the way across the row, which was a limitation of `table` elements.
After this PR, the background color actually takes up X% of the row.
Before:
After:
=> Instead of tables, use divs + css grid

app/analytics/query.test.ts, app/analytics/query.ts, app/analytics/schema.ts, app/components/PaginatedTableCard.tsx, app/components/SearchFilterBadges.tsx, app/components/TableCard.tsx, app/lib/types.ts, app/lib/utils.test.ts, app/lib/utils.ts, app/routes/dashboard.test.tsx, app/routes/dashboard.tsx, app/routes/resources.browser.tsx, app/routes/resources.country.tsx, app/routes/resources.device.tsx, app/routes/resources.paths.tsx, app/routes/resources.referrer.tsx, tailwind.config.js
_Note this targets the `v2` branch_
Now if users click a row within a table card, the full data set will be filtered by that selection.
For example, if in the "Paths" card, you click a given path (e.g. "/dashboard"), the dataset will reload filering on `path"=/dashboard"`. This means every figure – the top-level numbers, the chart, and all the table cards – will respect that filter.
You can also combine multiple filters (e.g. by referrer _and_ device).
---
**Still left to do:**
https://github.com/user-attachments/assets/e50a3abf-0673-4f47-ac49-3d70f328f8ce
=> Feature: Drill-down filters when clicking table rows [draft]

app/components/ui/table.tsx, app/root.tsx, app/routes/dashboard.tsx, tailwind.config.js
I've been finding that Counterscale's UI was just a little too "chunky" (lots of padding everywhere), which made viewing the app on a 14" MBP pretty challenging.
This PR attempts to reduce padding and text size around the app to make things a little more appealing:
* Reduce padding and text size of header (the row with "Counterscale")
* Reduce the height of the chart by 10%
* Reduce table padding from 3rem to 2rem
On my 14" MBP, after these changes, I can now see about 4.5 rows of table data (e.g. counts by path or referrer), whereas it was only 2 before.
Before:
After:
=> Tighten UI density

app/analytics/__tests__/query.test.ts, app/analytics/query.ts, app/routes/dashboard.tsx, package-lock.json
Refs #3 
---
This pull request introduces several improvements and new features:
- Refactor `intervalToSql` function to return both start and end interval SQL for better accuracy.
- Update test cases to reflect changes in interval handling.
- Adjust various API calls to utilize both start and end interval SQL.
- Add support for "yesterday" interval in analytics queries.
- Update relevant test cases to cover the new "yesterday" interval.
- Extend generateEmptyRowsOverInterval function to handle "yesterday" interval correctly.
- Modify the dashboard loader and UI to support the "yesterday" interval option.
- Files Modified:
- `app/analytics/__tests__/query.test.ts`
- `app/analytics/query.ts`
- `app/routes/dashboard.tsx`
- `package-lock.json`
=> Enhance Date Interval Handling and Add "Yesterday" Interval Support

app/analytics/query.ts, app/components/PaginatedTableCard.tsx, app/components/TimeSeriesChart.tsx, app/lib/utils.ts, app/routes/__tests__/dashboard.test.tsx, app/routes/dashboard.tsx, app/routes/resources.browser.tsx, app/routes/resources.country.tsx, app/routes/resources.device.tsx, app/routes/resources.paths.tsx, app/routes/resources.referrer.tsx, app/routes/resources.stats.tsx, app/routes/resources.timeseries.tsx
Fixes #109 and #107
This is a major change that removes all server-side rendered React, so that the app can first inspect the user's browser timezone, and pass that along to every component.
By doing so, we avoid having to use Cloudflare Worker's `cf.timezone` property, which can create confusing scenarios (like #107) when the user's internet doesn't route through the timezone they're located in (e.g. when using a VPN or proxy).
=> Refactor data fetching to use browser timezone, remove server rendering

app/analytics/query.ts
Daylight savings hack. Cloudflare Workers uses a different Date implementation than Node 20.x, which doesn't seem to respect DST boundaries the same way (see: #108).
To work around this, instead of adding 1 day, we add 25 hours every increment (intentionally overshooting), then grab the start of the day from that time, and repeat. This works in both Node 20.x and the production Cloudflare Workers environment.
NOTE: There's already a DST boundary test, but it was always passing since it was running in a Node environment.
=> Fix DST boundary issue occurring on Cloudflare env (fixes #108)

app/components/PaginatedTableCard.tsx, app/routes/resources.stats.tsx, app/routes/resources.timeseries.tsx
This does a few things:
- In `PaginatedTableCard`, refactors `page` to be a state variable (using `useState`), with corresponding data fetches occurring automatically via `useEffect`
- Instead of manually assembling query strings when calling `dataFetcher.load`, instead passes a dictionary of params to `dataFetcher.submit`
- Removes redundant `useEffect` calls with no dependencies (these didn't do anything)
- Removes some eslint warnings
=> Reduce card data fetching complexity

app/analytics/__tests__/collect.test.ts, app/analytics/__tests__/query.test.ts, app/analytics/collect.ts, app/analytics/query.ts, app/analytics/schema.ts, app/routes/__tests__/dashboard.test.tsx, app/routes/__tests__/resources.stats.test.tsx, app/routes/resources.stats.tsx
Adds tracking of bounces to `collect.ts` and `query.ts`. The implementation follows the approach outlined in the article https://notes.normally.com/cookieless-unique-visitor-counts/. I modified the existing implementation in `collect.ts` a bit to actually increment the `Last-Modified` header by one second instead of putting the current time. This is closer to the implementation in the article and allows the code to dynamically calculate the visits and determine the bounce value. Once the bounce value is determined it is written by the analytics engine.
**Side note**: I did not want to touch the `checkVisitorSession` function but maybe it would be a good idea to merge this with the `getBounce` function?
In `query.ts` I updated the queries to also return the bounce value.
In …
=> Adding Bounce Tracking

app/analytics/__tests__/query.test.ts, app/analytics/query.ts, app/routes/__tests__/resources.paths.test.tsx, app/routes/__tests__/resources.referrer.test.tsx
Fixes #122
I realize now getAllCountsByColumn had flawed logic; it was trying to get the top N rows, but also trying to simultaneously get data for visitors and views which doesn't work because that needs 2x the rows, and the `count` properties might not return in the same order either.
So instead this makes two queries:
1. First, queries the column by visitor count. This first query determines the order (so the rows are sorted by visitor count, not view count).
2. Then, make another query by _view_ count, using a `WHERE $column IN ($columnVal1, $columnVal1, ... $columnVal1)` clause from the results of the first query.
This is slower of course, but it seems unavoidable the way Analytics Engine works.
=> Fix pagination in getAllCountsByColumn

app/analytics/__tests__/query.test.ts, app/analytics/query.ts, app/components/TimeSeriesChart.tsx, app/routes/__tests__/resources.timeseries.test.tsx, app/routes/resources.stats.tsx, app/routes/resources.timeseries.tsx
Now that bounce data is available via #116, decided to add this and visitors to the timeseries chart.
Screenshot:
=> Add visitors + bounce rate to timeseries chart

app/components/TimeSeriesChart.tsx, app/components/ui/table.tsx, app/globals.css, app/routes/__tests__/resources.timeseries.test.tsx, app/routes/resources.timeseries.tsx, tailwind.config.ts
=> Improved chart tooltip

app/analytics/__tests__/query.test.ts, app/analytics/query.ts
Fix for issue #126 
Added the key filter to the `filterStr` if `keys.length > 0`
=> Handle empty key array

package-lock.json
Done by running `npm audit fix` and quickly verifying everything works in production (on a preview branch).
Before:
```
20 vulnerabilities (11 low, 4 moderate, 5 high)
```
After:
```
10 low severity vulnerabilities
```
=> Upgrade npm deps to address high-sev vulnerabilities (fixes #118)

packages/server/app/analytics/__tests__/collect.test.ts, packages/server/app/analytics/collect.ts, packages/server/app/analytics/query.ts, packages/server/app/analytics/schema.ts, packages/server/app/lib/__tests__/utils.test.ts, packages/server/app/lib/types.ts, packages/server/app/lib/utils.ts, packages/server/app/routes/__tests__/dashboard.test.tsx, packages/server/app/routes/__tests__/resources.browserversion.test.tsx, packages/server/app/routes/dashboard.tsx, packages/server/app/routes/resources.browserversion.tsx
Adds tracking of browser versions to Counterscale. The implementation updates the dashboard so that when a browser name is specified in the search filters we replace `BrowserCard` with `BrowserVersionCard` to list browser versions.
- **collect.ts**: adding browser version tracking
- **query.ts**: added query to count browser versions
- **dashboard.tsx**: conditional render of browser version card
- **resources.browserversion.tsx**: new card for displaying browser versions
Example deployed at https://dc458fa5.counterscale-7bi.pages.dev/dashboard?site=counterscale-dev&interval=today&browserName=Chrome&browserVersion=131.0.0.0
Originally we see the dashboard:
After clicking on `Chrome`, we replace `BrowserCard` with `BrowserVersionCard`:
I had an issue with testing `dashboard.test.tsx` where …
=> Adding browser version tracking

packages/server/functions/collect.ts
When converting to React Router 7, while trying to address some TypeScript typing issues, I made the mistake of not returning a proper `Response` object in the `/collect` Pages handler.
This meant that `/collect` was 1) writing the data, but 2) returning a 500 afterwards, which likely led to a host of issues like not setting `If-Modified-Since` headers properly (refs #148). This bug didn't appear in tests, nor using the Vite development server, which I mostly use for local development.
This highlights how the Pages function handlers need to be covered by tests, but on the flip side, they're being removed on the `v3` branch underway.
=> Return proper Response object in Pages function

packages/server/app/analytics/__tests__/collect.test.ts, packages/server/app/analytics/collect.ts
There are browser plugins [that strip the query string](https://addons.mozilla.org/en-US/firefox/addon/clearurls/) from some URLs. They're used by a small minority of browser users, but just a few stripped requests can cause blank data to enter Counterscale instances, causing issues like #150.
This PR amends the collect handler to reject blank/empty string values for `sid`, and returns a 400 instead.
cc @tycobrah
=> Reject blank site IDs (fixes #150)

packages/cli/src/__tests__/cloudflare.test.ts, packages/cli/src/cloudflare.ts, packages/cli/src/install.ts, packages/server/app/__tests__/root.test.tsx, packages/server/app/root.tsx, packages/server/package.json
It's a little more sophisticated this time:
If deployed from a clone (i.e. during development), will use the HEAD git sha as "version". Clicking the link brings you to that commit on GitHub.
If deployed using the CLI (e.g. via `npx @counterscale/cli install`), will use the current release version as declared in package.json (e.g. v3.0.0). Clicking the link brings you to the release notes on GitHub for that release.
Fixes #174
=> fix: Render version at the bottom of layout (again)

packages/server/app/analytics/__tests__/collect.test.ts, packages/server/app/analytics/collect.ts, packages/server/app/analytics/query.ts, packages/server/app/analytics/schema.ts, packages/server/app/components/PaginatedTableCard.tsx, packages/server/app/components/TableCard.tsx, packages/server/app/routes/__tests__/resources.device.test.tsx, packages/server/app/routes/resources.device.tsx
The idea thinking that it's more useful to understand device types (desktop, mobile, tablet, console) than to get an often-inaccurate breakdown of individual device types.
This makes the following changes:
* The `/collect` endpoint now extracts device type from the user agent and writes to `blob10`
* The Device card now queries from this column instead of `blob7` (`deviceModel`)
* `deviceModel` becomes pseudo-deprecated; it is still being written to the database, but it is no longer read back (to be revisited)
Once device type becomes populated, the device card should look like this:
I've deployed this version to `counterscale.dev` to observe production data for a while first.
Refs #168
=> feat: Use device type instead of model for Device card

packages/server/app/analytics/query.ts, packages/server/app/lib/__tests__/utils.test.ts, packages/server/app/lib/types.ts, packages/server/app/lib/utils.ts, packages/server/app/routes/resources.device.tsx
Clicking a device type should filter all queries (charts, table cards) by that device type.
This regression was introduced in #175 when device _model_ became device _type_.
Refs #119
=> fix: Device type filters

packages/server/app/analytics/collect.ts, packages/server/app/routes/__tests__/cache.test.tsx, packages/server/app/routes/__tests__/collect.test.tsx, packages/server/app/routes/cache.tsx, packages/tracker/src/__tests__/index.spec.ts, packages/tracker/src/lib/__tests__/track.spec.ts, packages/tracker/src/lib/request.ts, packages/tracker/src/lib/track.ts
Remove the `b` (bounce value) and `v` (visit) parameters in favor of a single parameter, `ht` (hit type).
Hit type represents 3 possible states:
1. this is a new visitor (records the event as a new visitor and assumes the user bounced)
2. this is the _first_ repeat visit (not a new visitor, negates the earlier bounce by using a bounce value of `-1`)
3. this is any subsequent repeat visit (not a new visitor, not a bounce)
I think this has the benefit of avoiding exposing internal values, and simplifies the API surface area (just a single parameter, `ht`, with only 3 possible values).
Additionally snuck in a fix to the tracker to avoid CORS preflight requests (was setting wrong Content-Type)
=> Simplify cache API (refs #180)

packages/server/app/routes/admin-redirect.tsx
fix: update admin redirect URL to correct Cloudflare path
The root URL for CF Workers and Pages now is /workers-and-pages but since counterscale is a worker, this is the new URL in their dashboard
=> fix: Admin redirect

README.md, packages/tracker/src/__tests__/index.spec.ts, packages/tracker/src/index.ts
Fixes #188
- Return silently from `Counterscale.init()` instead of throwing when a client is already initialized
- Adds `Counterscale.isInitialized()` - a convenience method if you need to know if a client exists but don't need the client itself
- Adds `Counterscale.getInitializedClient()` - returns a client if one exists, otherwise returns undefined
- Also adds docs for all `Counterscale.*` methods in the root README
=> Improve init and add related functions

packages/server/app/components/TableCard.tsx
In #216 I introduced a regression where `ExternalLink` icons were rendered for all labels, not just those that match the previous regex
=> fix: rm duplicate external link icon

packages/tracker/integration/01_legacyInit/index.html, packages/tracker/integration/02_dataAttrsInit/index.html, packages/tracker/integration/03_pushState/index.html, packages/tracker/src/__tests__/index.spec.ts, packages/tracker/src/lib/__tests__/track.spec.ts, packages/tracker/src/lib/client.ts, packages/tracker/src/lib/track.ts, packages/tracker/src/tracker.ts
Closes #50 
- adds a new boolean option to `Counterscale.init` named `reportOnLocalhost` (defaults to `false`) that enables/disables collecting events when the page is localhost, or any local IP address
- for those using the tracker script, add a `data-report-localhost` to the tracker's script tag to enable tracking on localhost
- If using a templating engine like JSX, you can use booleans to conditionally enable reporting on localhost via the tracker script (ie `data-report-localhost={isDev ? true : false }`
=> tracker: add localhost tracking configuration

packages/server/app/components/TableCard.tsx
**Description**: This PR updates the TableCard component to properly wrap long URLs, preventing layout overflow and improving readability. Previously, long URLs could break the table layout or extend beyond the visible area. With this change, URLs will wrap within their container, ensuring a cleaner and more user-friendly display.
**Changes**:
Added CSS styles to enable word wrapping for long URLs in the table.
Verified that table layout remains consistent with various URL lengths.
No impact on other components or functionality.
Motivation: Improves UI/UX by handling edge cases where URLs are excessively long, ensuring the table remains usable and visually appealing.
**Testing**:
Manually tested with short and long URLs.
Confirmed that wrapping works on Chrome and Firefox.
**Before …
=> Fix: Wrap Long URLs in TableCard Component

packages/server/app/analytics/__tests__/collect.test.ts, packages/server/app/analytics/__tests__/query.test.ts, packages/server/app/analytics/collect.ts, packages/server/app/analytics/query.ts, packages/server/app/analytics/schema.ts, packages/server/app/lib/__tests__/utils.test.ts, packages/server/app/lib/types.ts, packages/server/app/lib/utils.ts, packages/server/app/routes/__tests__/dashboard.test.tsx, packages/server/app/routes/__tests__/resources.utm-campaign.test.tsx, packages/server/app/routes/__tests__/resources.utm-content.test.tsx, packages/server/app/routes/__tests__/resources.utm-medium.test.tsx, packages/server/app/routes/__tests__/resources.utm-source.test.tsx, packages/server/app/routes/__tests__/resources.utm-term.test.tsx, packages/server/app/routes/dashboard.tsx, packages/server/app/routes/resources.utm-campaign.tsx, packages/server/app/routes/resources.utm-content.tsx, packages/server/app/routes/resources.utm-medium.tsx, packages/server/app/routes/resources.utm-source.tsx, packages/server/app/routes/resources.utm-term.tsx, packages/tracker/integration/04_utmTracking/index.html, packages/tracker/integration/04_utmTracking/index.spec.ts, packages/tracker/integration/server.js, packages/tracker/src/lib/__tests__/track.spec.ts, packages/tracker/src/lib/track.ts
Closes #138 by adding utm support to the server (/collect endpoint), tracker and dashboard. Implementation is based on [this doc from Plausible](https://plausible.io/blog/utm-tracking-tags#types-of-utm-parameters)
- Adds UTM parameter extraction from URLs
- Adds support for UTM parameters in the /collect endpoint
- Adds UTM to schema (blob 11-15)
- Adds `getCountBy*` queries for all UTM parameters
- Adds loaders and components for querying and displaying UTM data (resources.utm-*.tsx)
- Integrates UTM cards into the dashboard
=> UTM Tracking

packages/cli/src/commands/__tests__/install.test.ts, packages/cli/src/commands/install.ts, packages/cli/src/lib/__tests__/cloudflare.test.ts, packages/cli/src/lib/cloudflare.ts
Closes #195 
Adds api bearer token verification during install using cloudflares verify endpoint. 
> [!NOTE]
> In order to verify a tokens permissions, the token entered needs to be created as a user level token with `API Tokens: Read`. IMO this complicates the setup process and limits what tokens can be used to deploy Counterscale, so we only do basic validation during install.
- Adds an async static method, `verifyToken`, to `CloudflareClient`
- When then use this method inside the install command
=> feat: token validation on install

packages/server/app/analytics/__tests__/query.test.ts, packages/server/app/analytics/query.ts
Closes #65 
Queries are now using fixed intervals (5 minutes) which is already causing the dashboard to load faster. As called out in the issue, we're using `toStartOfInterval` to achieve this
=> Use fixed intervals instead of NOW() in queries
